name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start NATS server
        run: |
          docker run -d --name nats -p 6789:6789 \
            -v ${{ github.workspace }}/nats.config:/my-nats.config \
            nats:latest --config /my-nats.config
          for i in {1..30}; do
            if nc -z 127.0.0.1 6789; then
              exit 0
            fi
            sleep 1
          done
          exit 1

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "28.5"
          gleam-version: "1.16.0"
          rebar3-version: "3"
          # elixir-version: "1"
      - run: gleam deps download
      - run: gleam test
      - run: gleam format --check src test

      - name: Print NATS logs on failure
        if: failure()
        run: docker logs nats
